title: Bill Peterson # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description:  # your text below (remove <br> elements if you don't need line breaks)
  <center>
  <b>Data Science & Applied Statistics</b>
  <br>
  <a href="https://www.linkedin.com/in/williambpeterson/">LinkedIn</a>
  <a> | </a>
  <a href="https://github.com/wbp2114">GitHub</a>    
  <br><br>
  </center>
  
  <b>Methodologies&#58; </b><br>
  &#8901; Econometric, spatial, time series, <br> 
   natural language processing and  <br>
   machine learning.  <br>
  <br>
  <b>Languages&#58; </b><br>
  &#8901; Proficient&#58; R and Python. <br>
  &#8901; Experienced&#58; QGIS, GeoDa and MS VBA. <br>
theme: jekyll-theme-minimal
google_analytics: UA-182108598-1 # your Google Analytics tracking ID here
