title: Bill Peterson # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
   <center>
  <b>Data Science & Applied Statistics</b>
  <br>
  <a href="https://www.linkedin.com/in/williambpeterson/">LinkedIn</a>
  <a> | </a>
  <a href="https://github.com/wbp2114">GitHub</a>    
  <br><br>
    </center>
  
  <b>Skilled in &#58; </b><br>
  &#8901; Econometric, spatial, time series, <br> 
  &#8901; natural language processing and  <br>
  &#8901; machine learning methods.  <br>
  <br>
  &#8901; Proficient in R and Python. <br>
  &#8901; Experienced in QGIS and GeoDa. <br>
theme: jekyll-theme-minimal
google_analytics: UA-182108598-1 # your Google Analytics tracking ID here
